experimental/multiple-versions-in-one-file
php nixpkgs:
  PHP: fpm support (including patches for systemd socket activation)
  nixos systemd unit implementation

  make PHP know about /var/setuid-wrappers/sendmail (path is configurable)

  keep everything in one file, because most code is the same, eg the code to
  build extensions (apc, xdebug, ..)

  There have been quite a lot of changes in nixpkgs master. I think I merged
  all changes.

  keep supporting PHP 5.3 because PHP 5.3 and 5.4 are not compatible always
  I know I should upgrade ...

nixos:
  provide php-fpm module which figures out how many php-fpm daemoens to use
  automatically. Its still your task to to configure apache/ nginx.
  You do so by using a function returning the socket path based on
  your configuration.
  nixos/modules/services/misc/phpfpm.nix contains a usage example.

  Enabling xdebug is very easy now, see example at
  nixos/modules/services/misc/phpfpm.nix

  Same to enabling opcache.

  replace nixos/modules/services/web-servers/phpfpm.nix
  by nixos/modules/services/misc/phpfpm.nix
  because its more powerful

Till this gets merged you can follow the topic branch experimental/php at
github.com/MarcWeber/nixpkgs.

Signed-off-by: Marc Weber <marco-oweber@gmx.de>

diff --git a/pkgs/development/interpreters/php/fix.patch b/pkgs/development/interpreters/php/fix.patch
--- a/pkgs/development/interpreters/php/fix.patch
+++ b/pkgs/development/interpreters/php/fix.patch
@@ -1,7 +1,6 @@
-diff -ru php-5.4.14/configure php-5.4.14-new/configure
---- php-5.4.14/configure	2013-04-10 09:53:26.000000000 +0200
-+++ php-5.4.14-new/configure	2013-04-22 17:13:55.039043622 +0200
-@@ -6513,7 +6513,7 @@
+--- php-5.0.4/configure	2005-04-03 11:42:50.000000000 +0200
++++ php-5.0.4-1/configure	2005-07-10 11:06:22.292271176 +0200
+@@ -3381,7 +3381,7 @@
  
    case $host_alias in
    *aix*)
@@ -10,17 +9,17 @@ diff -ru php-5.4.14/configure php-5.4.14-new/configure
      EXTRA_LDFLAGS="$EXTRA_LDFLAGS -Wl,-brtl -Wl,-bI:$APXS_LIBEXECDIR/httpd.exp"
      PHP_AIX_LDFLAGS="-Wl,-brtl"
      build_type=shared
-@@ -6706,7 +6706,7 @@
+@@ -3576,7 +3576,7 @@
    if test "$?" != "0"; then
      APACHE_INSTALL="$APXS -i -a -n php5 $SAPI_SHARED" # Old apxs does not have -S option
-   else
+   else 
 -    APXS_LIBEXECDIR='$(INSTALL_ROOT)'`$APXS -q LIBEXECDIR`
 +    APXS_LIBEXECDIR="$prefix/modules"
      if test -z `$APXS -q SYSCONFDIR`; then
        APACHE_INSTALL="\$(mkinstalldirs) '$APXS_LIBEXECDIR' && \
                         $APXS -S LIBEXECDIR='$APXS_LIBEXECDIR' \
-@@ -7909,7 +7909,7 @@
-    { (exit 1); exit 1; }; }
+@@ -4680,7 +4680,7 @@
+     { echo "configure: error: Please note that Apache version >= 2.0.40 is required." 1>&2; exit 1; }
    fi
  
 -  APXS_LIBEXECDIR='$(INSTALL_ROOT)'`$APXS -q LIBEXECDIR`
@@ -28,8 +27,8 @@ diff -ru php-5.4.14/configure php-5.4.14-new/configure
    if test -z `$APXS -q SYSCONFDIR`; then
      INSTALL_IT="\$(mkinstalldirs) '$APXS_LIBEXECDIR' && \
                   $APXS -S LIBEXECDIR='$APXS_LIBEXECDIR' \
-@@ -8779,7 +8779,7 @@
-    { (exit 1); exit 1; }; }
+@@ -5510,7 +5510,7 @@
+     { echo "configure: error: Please note that Apache version >= 2.0.44 is required." 1>&2; exit 1; }
    fi
  
 -  APXS_LIBEXECDIR='$(INSTALL_ROOT)'`$APXS -q LIBEXECDIR`
@@ -37,7 +36,7 @@ diff -ru php-5.4.14/configure php-5.4.14-new/configure
    if test -z `$APXS -q SYSCONFDIR`; then
      INSTALL_IT="\$(mkinstalldirs) '$APXS_LIBEXECDIR' && \
                   $APXS -S LIBEXECDIR='$APXS_LIBEXECDIR' \
-@@ -9634,7 +9634,7 @@
+@@ -6327,7 +6327,7 @@
  
    case $host_alias in
    *aix*)
@@ -46,24 +45,34 @@ diff -ru php-5.4.14/configure php-5.4.14-new/configure
      EXTRA_LDFLAGS="$EXTRA_LDFLAGS -Wl,-brtl -Wl,-bI:$APXS_LIBEXECDIR/httpd.exp"
      PHP_AIX_LDFLAGS="-Wl,-brtl"
      build_type=shared
-@@ -9827,7 +9827,7 @@
+@@ -6522,7 +6522,7 @@
    if test "$?" != "0"; then
      APACHE_HOOKS_INSTALL="$APXS -i -a -n php5 $SAPI_SHARED" # Old apxs does not have -S option
-   else
+   else 
 -    APXS_LIBEXECDIR='$(INSTALL_ROOT)'`$APXS -q LIBEXECDIR`
 +    APXS_LIBEXECDIR="$prefix/modules"
      if test -z `$APXS -q SYSCONFDIR`; then
        APACHE_HOOKS_INSTALL="\$(mkinstalldirs) '$APXS_LIBEXECDIR' && \
                         $APXS -S LIBEXECDIR='$APXS_LIBEXECDIR' \
-@@ -59657,9 +59657,7 @@
- 
- 
- if test "$PHP_GETTEXT" != "no"; then
--  for i in $PHP_GETTEXT /usr/local /usr; do
--    test -r $i/include/libintl.h && GETTEXT_DIR=$i && break
--  done
-+  GETTEXT_DIR=$PHP_GETTEXT
- 
-   if test -z "$GETTEXT_DIR"; then
-     { { $as_echo "$as_me:$LINENO: error: Cannot locate header file libintl.h" >&5
-
+diff -rc php-5.3.18/configure php-5.3.18-new/configure
+*** php-5.3.18/configure	2012-10-17 18:29:10.000000000 +0200
+--- php-5.3.18-new/configure	2012-11-13 05:36:24.730136551 +0100
+***************
+*** 45113,45121 ****
+  
+  
+  if test "$PHP_GETTEXT" != "no"; then
+!   for i in $PHP_GETTEXT /usr/local /usr; do
+!     test -r $i/include/libintl.h && GETTEXT_DIR=$i && break
+!   done
+  
+    if test -z "$GETTEXT_DIR"; then
+      { echo "configure: error: Cannot locate header file libintl.h" 1>&2; exit 1; }
+--- 45113,45119 ----
+  
+  
+  if test "$PHP_GETTEXT" != "no"; then
+!   GETTEXT_DIR=$PHP_GETTEXT
+  
+    if test -z "$GETTEXT_DIR"; then
+      { echo "configure: error: Cannot locate header file libintl.h" 1>&2; exit 1; }
